# Generated by Django 3.2 on 2022-02-06 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size_code',
        ),
    ]
