# Generated by Django 3.2 on 2022-02-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_size_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TyreSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.CharField(max_length=3)),
                ('heigth', models.CharField(max_length=2)),
                ('rim_size', models.CharField(max_length=2)),
                ('full_size_code', models.CharField(max_length=8)),
                ('full_size_display', models.CharField(max_length=10)),
            ],
        ),
    ]
