# Generated by Django 3.2 on 2022-02-06 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tyresize',
            name='full_size_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='tyresize',
            name='full_size_display',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tyresize',
            name='heigth',
            field=models.PositiveIntegerField(default=55, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AlterField(
            model_name='tyresize',
            name='rim_size',
            field=models.PositiveIntegerField(default=16, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(26)]),
        ),
        migrations.AlterField(
            model_name='tyresize',
            name='width',
            field=models.PositiveIntegerField(default=125, validators=[django.core.validators.MinValueValidator(125), django.core.validators.MaxValueValidator(345)]),
        ),
    ]
