# Generated by Django 3.2 on 2022-02-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20220206_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ean',
            new_name='ean_code',
        ),
    ]
