# Generated by Django 3.2 on 2022-02-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_tyresize_full_size_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyresize',
            name='full_size_sort',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
